### ISSUE TITLE
Create Main Panel Component

### ISSUE THREAD

**Issue by legomushroom** [legomushroom/mojs-timeline-editor#1]
# ⚠️ @EugeneChu is currently working on this one ⚠️

Please read the [help wanted guide](https://github.com/legomushroom/mojs-timeline-editor/blob/master/help-wanted.md) before start.

![main panel](https://cloud.githubusercontent.com/assets/1478800/19604654/d1d91760-977b-11e6-9e84-830749a28d02.png)

Create `react` (`preact`) component of the main panel. It should have `position: fixed`, be at the bottom and take all width of the window.
It will have child panels - `left` and `right`:
- the `left` panel is fixed size of `165px`.
- the `right` panel is fluid width of `totalWidth - left panel width`

And two buttons:
- resize button: you can drag and resize the panel vertically
- hide button: you can switch the state of the panel by clicking on the button, just like [mojs-player](http://codepen.io/sol0mka/pen/vXdVBm) can.
- both buttons are exact in the center of the `right` child panel.

Please note that the panel can have optional `MojsPlayer` at the bottom, so be sure that the panel doesn't go less than `40px` while `hide` and `resize` happens. Component will receive `player` property that will define if player is present. Illustration with `MojsPlayer` at the bottom:

![timeline-editor 2x](https://cloud.githubusercontent.com/assets/1478800/19605584/cb844ec0-9780-11e6-851a-866bf42246d5.png)

`hide` and `resize` buttons are separate components. Those have been used in [mojs-player](https://github.com/legomushroom/mojs-player) and [mojs-curve-editor](https://github.com/legomushroom/mojs-curve-editor) repos so you can copy them.

The sketch mockup - [main-panel.zip](https://github.com/legomushroom/mojs-timeline-editor/files/544869/main-panel.zip)

Cheers!

**Comment by dev99problems** [comment]
Will do

**Comment by legomushroom** [comment]
## thanks, @EugeneChu! 👍 🎉 

https://github.com/legomushroom/mojs-timeline-editor/pull/4
