### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by jamylak** [legomushroom/mojs-timeline-editor#12]
Can we please add in readme how to initialise this and pass in a timeline? 

I seem to be getting that "is not a constructor"

**Comment by xavierfoucrier** [comment]
Hi @jamylak!

The timeline editor seems to not be released yet... but you can still play with the UI by just including the `app/build/mojs-timeline-editor.js` after `mo.min.js`. This will display the editor and you will be able to create points, add/edit properties, etc. No more code required.

By checking the source code, the timeline editor has built-in shortcuts, but it seems that they are not working on my dev environment, Win x64. If you find a solution for this problem, please keep me informed.

Furthermore, I have not tested to add `Tween` or entire `Timeline` to the editor.

Best regards. :+1:
