### ISSUE TITLE
Create timeline panel

### ISSUE THREAD

**Issue by legomushroom** [legomushroom/mojs-timeline-editor#2]
# ⚠️ @EugeneChu is currently working on this one ⚠️

Please read the [help wanted guide](https://github.com/legomushroom/mojs-timeline-editor/blob/master/help-wanted.md) before start.

![timeline panel](https://cloud.githubusercontent.com/assets/1478800/19700532/508f9284-9abd-11e6-8ac4-8f4ccfa40bc8.png)

Create `react` (`preact`) component of the timeline panel. It should take `100%` of parent `width`.

The precise sizes in pixels:

![image](https://cloud.githubusercontent.com/assets/1478800/19699742/22e56ab4-9aba-11e6-981f-8b99501b4232.png)

Colors:
- small dash: `#AE9BAE`
- large dash and number label: `white`
- purple background: `#512750`

Shadow of the panel: `0 2px 4px black`

All time labels are exactly in the middle of the large dash.
## Requirements for the component

As you can notice from size illustration, gap between dashes is `4px`, it should be defined in `em` units. So if you set `font-size` on the root of the component to `10px`, the gap should be set to `0.4em` so the result will be equal to `4px`. 
Having that component will receive `scale` property and the timeline will be scaled accordingly, simply by setting root's `font-size` to appropriate value. For instance, if `scale` property is `1.5` the `font-size` should be set to `10` \* `1.5` = `15px`. This will allow to `scale` the timeline by means of `em` units. All other sizes must not use `em`s, only the size of dash gap should scale.

The timeline should cover at least `20 seconds` or `20 000 milliseconds`.

Entire sketch mockup could be found here: [link](https://github.com/legomushroom/mojs-timeline-editor/files/551658/timeline.task.zip) and here [link](https://github.com/legomushroom/mojs-timeline-editor/blob/master/mockups/point-editor.sketch?raw=true).

Cheers! ~

**Comment by dev99problems** [comment]
Will do
