### ISSUE TITLE
Cut Timeline Handle Into Component

### ISSUE THREAD

**Issue by legomushroom** [legomushroom/mojs-timeline-editor#3]
Please read the [help wanted guide](https://github.com/legomushroom/mojs-timeline-editor/blob/master/help-wanted.md) before start.

**Illustration:**

<img src="https://cloud.githubusercontent.com/assets/1478800/19701634/cf3ccf1c-9ac1-11e6-9bcf-eb36525ac875.png" alt="timeline handle" width="20" />

**Task:**

Create `react` (`preact`) component of the timeline handle. It should take `100%` of parent `height` and should be shifted `-10px top` :

![cut timeline](https://cloud.githubusercontent.com/assets/1478800/19701785/8a9bd55a-9ac2-11e6-8899-02a833d5a0b6.png)
## Colors:
- purple background: `#3D1B3C`
- orange: `#FF4F02`
- lines: `white`
## Component Requirements

It should receive `shift` prop and set that `shift` as `translateX` for the component.

Also it should receive `scale` prop that will affect the `translateX` value, regarding the simple formular: `translateX({shift * scale}px)`.

Component will have horizontal `drag/pan` event handler but that's not relevant right now.

Entire sketch mockup could be found here: [link](https://github.com/legomushroom/mojs-timeline-editor/files/551661/timeline.handle.task.zip) and here [link](https://github.com/legomushroom/mojs-timeline-editor/blob/master/mockups/point-editor.sketch?raw=true).

Cheers! ~

**Comment by dev99problems** [comment]
Will do

**Comment by legomushroom** [comment]
Hey, I was at the point where I need it asap, so implemented it myself.
