### ISSUE TITLE
Add eslint to the project

### ISSUE THREAD

**Issue by legomushroom** [legomushroom/mojs-timeline-editor#8]
Need to add `eslint-loader` to `webpack.config` and linting rules file. The file could be a [airbnb's eslint config](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb/rules) or [this one](https://github.com/legomushroom/cards-game/blob/master/.eslintrc).

**Comment by dev99problems** [comment]
Will do

**Comment by legomushroom** [comment]
Can we close this yet?

**Comment by dev99problems** [comment]
I think we can for now.
I have some ideas for improvements, but it would be better to create a new issue in the future.

**Comment by legomushroom** [comment]
thanks! 👍
